version: "3.3"
services:
  engine:
    container_name: recommend-engine
    build:
      context: ./packages/recommendationEngine
      dockerfile: Dockerfile.production
    restart: always
    network_mode: host
    ports: 
      - "8000:8000"
  backend:
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.production
    restart: always
    env_file: ./packages/backend/.env
    network_mode: host
    ports:
      - "3001:3001"
  frontend:
    container_name: frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.production
    restart: always
    env_file: ./packages/frontend/.env
    network_mode: host
    ports:
      - "3000:3000"
